// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hello_EF.Migrations
{
    [DbContext(typeof(PetContext))]
    [Migration("20240619192308_many2many")]
    partial class many2many
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Owner", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("OwnerPet", b =>
                {
                    b.Property<int>("OwnedPetID")
                        .HasColumnType("int");

                    b.Property<int>("PetOwnersID")
                        .HasColumnType("int");

                    b.HasKey("OwnedPetID", "PetOwnersID");

                    b.HasIndex("PetOwnersID");

                    b.ToTable("OwnerPet");
                });

            modelBuilder.Entity("Pet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Cuteness")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PetSpeciesID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PetSpeciesID");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("Species", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("OwnerPet", b =>
                {
                    b.HasOne("Pet", null)
                        .WithMany()
                        .HasForeignKey("OwnedPetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Owner", null)
                        .WithMany()
                        .HasForeignKey("PetOwnersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pet", b =>
                {
                    b.HasOne("Species", "PetSpecies")
                        .WithMany()
                        .HasForeignKey("PetSpeciesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PetSpecies");
                });
#pragma warning restore 612, 618
        }
    }
}
